NCKH_django/NCKH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from register import views as v
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name='register'),
    path('', include('django.contrib.auth.urls')),
    path('home/', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('properties/', include('properties.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

NCKH_django/about/urls.py
from django.urls import path
from . import views
app_name = 'about'
urlpatterns = [
    path('', views.about, name = 'about'),
]

NCKH_django/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.homeIndex.as_view(),name='home'),
    path('create/', views.create,name='create'),
]

NCKH_django/properties/urls.py
from django.urls import path
from . import views

app_name = 'properties'
urlpatterns = [
    # properties
    path('', views.getProperty, name='getProperties'),
    path('postProperties/', views.postProperty, name='postProperties'),
    
    # favorites
    path('favoritesList/', views.getfavoritesList, name='getFavoritesList'),
    path('favoritesList/postFavoritesList',views.postProperty, name='postFavoritesList'),
    
    # search
    path('searchList/', views.getSearchList, name='getSearch'),
    path('postSearchList/', views.postSearchList, name='postSearchList'),
    
    path('like/', views.like_user, name='like-user'),
    
    # path('Details/',views.Details_house, name='getDetails'),
    path('<int:id>/',views.Details_house, name='getDetails'),
    path('Details/postDetails/',views.PostDetails_house, name='postDetails'),
]

NCKH_django/about/models.py
from django.db import models

# Create your models here.

NCKH_django/about/templates/about/about.html
{% extends "home/base.html" %} {% load static %} {% block title %}About | Alte - Real estate | Find your future home{% endblock %} {% block link %}
<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'about/style.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<!-- Header Start -->
<div class="container-fluid page-header">
    <div class="container">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
            <h3 class="display-4 text-white text-uppercase">About</h3>
            <div class="d-inline-flex text-white">
                <p class="m-0 text-uppercase">
                    <a class="text-white" href="{% url 'home:home' %}">Home</a>
                </p>
                <i class="fa fa-angle-double-right pt-1 px-3"></i>
                <p class="m-0 text-uppercase">About</p>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->

<!-- About Start -->
<div class="container-fluid py-5">
    <div class="container pt-5">
        <div class="row">
            <div class="col-lg-6" style="min-height: 500px;">
                <div class="position-relative h-100">
                    <img class="position-absolute w-100 h-100" src="{% static 'images/about/about.jpg' %}" style="object-fit: cover;">
                </div>
            </div>
            <div class="col-lg-6 pt-5 pb-lg-5">
                <div class="about-text bg-white p-4 p-lg-5 my-lg-5">
                    <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">About Us</h6>
                    <h1 class="mb-3">We Provide Best Place In Your Budget</h1>
                    <p>Dolores lorem lorem ipsum sit et ipsum. Sadip sea amet diam dolore sed et. Sit rebum labore sit sit ut vero no sit. Et elitr stet dolor sed sit et sed ipsum et kasd ut. Erat duo eos et erat sed diam duo</p>
                    <div class="row mb-4">
                        {% for HouseListItems in HouseList %}
                        <div class="col-6">
                            <img class="img-fluid" style="height:160px" src="{{ MEDIA_URL }}{{ HouseListItems.14}}" alt="">
                        </div>
                        
                        {% endfor %}
                    </div>
                    <a href="{% url 'properties:getProperties' %}" class="btn btn-primary mt-1">Book Now</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->


<!-- Feature Start -->
<div class="container-fluid pb-5">
    <div class="container pb-5">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="d-flex mb-4 mb-lg-0">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-primary mr-3" style="height: 100px; width: 100px;">
                        <i class="fa fa-2x fa-money-check-alt text-white"></i>
                    </div>
                    <div class="d-flex flex-column">
                        <h5 class="">Competitive Pricing</h5>
                        <p class="m-0">Magna sit magna dolor duo dolor labore rebum amet elitr est diam sea</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="d-flex mb-4 mb-lg-0">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-primary mr-3" style="height: 100px; width: 100px;">
                        <i class="fa fa-2x fa-award text-white"></i>
                    </div>
                    <div class="d-flex flex-column">
                        <h5 class="">Best Services</h5>
                        <p class="m-0">Magna sit magna dolor duo dolor labore rebum amet elitr est diam sea</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="d-flex mb-4 mb-lg-0">
                    <div class="d-flex flex-shrink-0 align-items-center justify-content-center bg-primary mr-3" style="height: 100px; width: 100px;">
                        <i class="fa fa-2x fa-globe text-white"></i>
                    </div>
                    <div class="d-flex flex-column">
                        <h5 class="">Worldwide Coverage</h5>
                        <p class="m-0">Magna sit magna dolor duo dolor labore rebum amet elitr est diam sea</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Feature End -->

<!-- Team Start -->
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Agents</h6>
            <h1>Our Agents</h1>
        </div>
        <div class="row">
            {% for HouseLessorItems in HouseLessor %}
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <div class="team-item bg-white mb-4">
                    <div class="team-img position-relative overflow-hidden">
                        <img class="img-fluid w-100" src="{{ MEDIA_URL }}{{ HouseLessorItems.4 }}" alt="">
                        <div class="team-social">
                            <a class="btn btn-outline-primary btn-square" href="{{ HouseLessorItems.7 }}"><i class="fab fa-facebook-f"></i></a>
                            
                        </div>
                    </div>
                    <div class="text-center py-4">
                        <h5 class="text-truncate">{{ HouseLessorItems.1 }}</h5>
                        <p class="m-0">Developer</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Team End -->


<!-- Footer Start -->

<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="mail/jqBootstrapValidation.min.js"></script>
<script src="mail/contact.js"></script>

<!-- Template Javascript -->
<script src="{% static 'about/main.js' %}"></script>
{% endblock %}